valine:
  enable: true
  appId: "blog-three-alpha-68.vercel.app"
  appKey: "1234qwer"
  serverURLs: "https://blog-three-alpha-68.vercel.app"
  placeholder: "说点什么吧~"
  avatar: "mm" # 默认头像风格
  meta: ["nick","mail","link"] # 可填写的字段
  pageSize: 10
  lang: "zh-CN"
  visitor: true